id: IEEBDF18C
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:01:43.881791
last_modified: 2023-02-09 15:01:43.881929
source_metadata:
  title: 'MSV 1,02: Poṣadhavastu'
  language: sa
bases:
  7A0F:
    base_file: 7A0F.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
